NumPy Complete Guide (All Major Functions)
# NumPy Complete Guide
This notebook covers the most important NumPy functions:
1. Basics & Array Creation
2. Indexing & Slicing
3. Reshaping & Manipulation
4. Mathematical & Statistical Functions
5. Linear Algebra
6. Random Module
7. File I/O & Utilities

In [1]:
import numpy as np


In [2]:
# From Python list
arr = np.array([1, 2, 3])
print("Array:", arr)

# Zeros, Ones, Empty, Full
print("\nZeros:\n", np.zeros((2, 3)))
print("\nOnes:\n", np.ones((3, 3)))
print("\nEmpty:\n", np.empty((2, 2)))
print("\nFull:\n", np.full((2, 2), 7))

# Range
print("\nArange:", np.arange(0, 10, 2))
print("\nLinspace:", np.linspace(0, 1, 5))

# Identity
print("\nIdentity:\n", np.eye(3))


Array: [1 2 3]

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Empty:
 [[2.54999477e-315 0.00000000e+000]
 [1.33511018e-306 1.33511562e-306]]

Full:
 [[7 7]
 [7 7]]

Arange: [0 2 4 6 8]

Linspace: [0.   0.25 0.5  0.75 1.  ]

Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
# Inspecting arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", a.shape)
print("Dimensions:", a.ndim)
print("Size:", a.size)
print("Dtype:", a.dtype)
print("Itemsize (bytes):", a.itemsize)


Shape: (2, 3)
Dimensions: 2
Size: 6
Dtype: int64
Itemsize (bytes): 8


In [4]:
# Type conversion
b = np.array([1.2, 3.4, 5.6])
print("Original dtype:", b.dtype)
print("Converted to int:", b.astype(int))


Original dtype: float64
Converted to int: [1 3 5]


2. Indexing & Slicing


In [5]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0], arr[-1])
print("Slice:", arr[1:4])
print("Every 2nd element:", arr[::2])

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Row 0:", arr2d[0, :])
print("Column 1:", arr2d[:, 1])


10 50
Slice: [20 30 40]
Every 2nd element: [10 30 50]
Row 0: [1 2 3]
Column 1: [2 5 8]


In [6]:
# Fancy indexing
arr = np.array([10, 20, 30, 40, 50])
print(arr[[0, 2, 4]])

# Boolean indexing
print(arr[arr > 25])


[10 30 50]
[30 40 50]


3. Reshaping & Manipulation

In [8]:
arr = np.arange(1, 13)
print("Original:", arr)

reshaped = arr.reshape(3, 4)
print("\nReshaped:\n", reshaped)

print("\nFlattened:", reshaped.flatten())
print("Raveled:", reshaped.ravel())

# Resize (in-place)
arr2 = np.array([[1, 2], [3, 4]])
arr2.resize((3, 3))
print("\nResized:\n", arr2)


Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Raveled: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Resized:
 [[1 2 3]
 [4 0 0]
 [0 0 0]]


In [9]:
# Joining arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Concatenate:", np.concatenate((a, b)))
print("Vstack:\n", np.vstack((a, b)))
print("Hstack:\n", np.hstack((a, b)))

# Splitting
arr = np.arange(1, 10)
print("Split into 3:", np.split(arr, 3))

mat = np.arange(16).reshape(4, 4)
print("Horizontal split:\n", np.hsplit(mat, 2))
print("Vertical split:\n", np.vsplit(mat, 2))


Concatenate: [1 2 3 4 5 6]
Vstack:
 [[1 2 3]
 [4 5 6]]
Hstack:
 [1 2 3 4 5 6]
Split into 3: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
Horizontal split:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
Vertical split:
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


4. Mathematical & Statistical Functions

In [10]:
arr = np.array([1, 2, 3, 4, 5])

print("Sum:", arr.sum())
print("Product:", arr.prod())
print("Mean:", arr.mean())
print("Median:", np.median(arr))
print("Std:", arr.std())
print("Var:", arr.var())
print("Min:", arr.min(), "at index", arr.argmin())
print("Max:", arr.max(), "at index", arr.argmax())

print("\nCumsum:", arr.cumsum())
print("Cumprod:", arr.cumprod())


Sum: 15
Product: 120
Mean: 3.0
Median: 3.0
Std: 1.4142135623730951
Var: 2.0
Min: 1 at index 0
Max: 5 at index 4

Cumsum: [ 1  3  6 10 15]
Cumprod: [  1   2   6  24 120]


In [11]:
# Universal functions
print("Exp:", np.exp(arr))
print("Log:", np.log(arr))
print("Sqrt:", np.sqrt(arr))
print("Sin:", np.sin(arr))
print("Cos:", np.cos(arr))
print("Round:", np.round([1.2, 2.6, 3.5]))


Exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Sqrt: [1.         1.41421356 1.73205081 2.         2.23606798]
Sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Round: [1. 3. 4.]


5. Linear Algebra

In [12]:
matA = np.array([[1, 2], [3, 4]])
matB = np.array([[5, 6], [7, 8]])

print("Dot product:\n", np.dot(matA, matB))
print("Matrix multiplication:\n", np.matmul(matA, matB))
print("Transpose:\n", matA.T)

print("Determinant:", np.linalg.det(matA))
print("Inverse:\n", np.linalg.inv(matA))
eigvals, eigvecs = np.linalg.eig(matA)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

b = np.array([5, 11])
solution = np.linalg.solve(matA, b)
print("Solution of Ax=b:", solution)


Dot product:
 [[19 22]
 [43 50]]
Matrix multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Solution of Ax=b: [1. 2.]


6. Random Module

In [13]:
np.random.seed(42)

print("Random uniform [0,1):", np.random.rand(3))
print("Random normal:", np.random.randn(3))
print("Random integers:", np.random.randint(1, 10, 5))

arr = np.arange(10)
print("Random choice:", np.random.choice(arr, 5, replace=False))


Random uniform [0,1): [0.37454012 0.95071431 0.73199394]
Random normal: [-1.11188012  0.31890218  0.27904129]
Random integers: [8 3 6 5 2]
Random choice: [8 2 9 6 0]


7. File I/O & Utilities

In [14]:
# Save & Load
arr = np.array([1, 2, 3, 4, 5])
np.save("my_array.npy", arr)
loaded = np.load("my_array.npy")
print("Loaded:", loaded)

# Save & load text
np.savetxt("my_array.txt", arr)
loaded_txt = np.loadtxt("my_array.txt")
print("Loaded txt:", loaded_txt)


Loaded: [1 2 3 4 5]
Loaded txt: [1. 2. 3. 4. 5.]


In [15]:
# Copy vs View
a = np.array([1, 2, 3])
b = a  # reference
c = a.copy()  # copy
a[0] = 99
print("a:", a)
print("b (reference):", b)
print("c (copy):", c)


a: [99  2  3]
b (reference): [99  2  3]
c (copy): [1 2 3]


In [16]:
# Utilities
arr = np.array([1, 2, 2, 3, 3, 3])
print("Unique:", np.unique(arr))
print("Where >2:", np.where(arr > 2))
print("Tile:", np.tile([1, 2], 3))
print("Repeat:", np.repeat([1, 2], 3))


Unique: [1 2 3]
Where >2: (array([3, 4, 5]),)
Tile: [1 2 1 2 1 2]
Repeat: [1 1 1 2 2 2]
